language: python
python:
- 2.7
branches:
  only:
  - master
cache:
  directories:
  - $HOME/.cache/pip
  - $HOME/pygrow
  - $HOME/virtualenv
env:
  global:
  - secure: "o0VA1qXI9ZWPwSRnMODjVPiVWtKF+4ZdimgFfYybbi7gIW0h5xboO/mBEnRLuUfCg3I2lx3SNpt7rxG/GDrwXtLEW1SPXJs4kRxfgWZZiwmWjBgF1PHjED2mw5uqbV9e/6b9OGzJ0uYzWH41Zjzcnv3BpZ/oWsCNTHub+SV9ycmg2ZgLEJNQKImGiKFRwLPnQQWeLcJChX2XdGH0oE+sXk0FtmSNzmoWBEpn8dG2UXSRcka4FvISsWU434hAUJsjzQCSVKey6ZlEvVNNIs77/i7Ba7LtvbObeJLrtp0ytSEO6rriFWN8K12DIdQxilPVrN+Lwx6+oSK1mqZFWjbtAiiMX137i2A934HqJH/L+2NrPKIWzyS4+ZHObwvaJHSahl4Z1htDWbmSRO4xwdIdo3/S8L9OpqB6wyJNZIVvF5tUqBtwNJ8fqYKG6ekzYh+GpAyfZ/oKIrZEAeMH2bHSGz8QF6JKLhoKbMQnpSPV32INl8kA67tY8Uf9UfrLQ0bn7cB2WHYFf+plCGZwaZUy8yWN+LY8AL3sG2hb2D597vCve252HYZazsunQTR3CMO4fWoZvS24XaGg73Av/WdHQicQnSGneVyhjsbmJpG97SN18fRptyyxy+e0Wl+AopQ9HEXSLHAzgAr+/wqsESWfl6aLBFO+wANgiqSvPp6NKeo="
install:
- bash ./install-grow.sh
- bash ./setup.sh
- git clone https://$GITHUB_TOKEN@github.com/stevenle/stevenle.github.io.git
script: bash ./deploy-travis.sh
